### ISSUE TITLE
Exe olarak paketleme ve arka planda çalıştırma.

### ISSUE THREAD

**Issue by enseitankado** [BatuHanHub/Window-Sniffer#2]
Program güzel çalışıyor, bahsettiğim değişiklikleri de yaparsan daha güzel olur. 

Şimdi sana yeni görevinden bahsediyorum. Bu ana görev değil sadece ek görev.

Tarif ediyorum:

Program python yorumlayıcısına parametre olarak verildiği için bir konsol penceresi içinde çalışıyor. 
1) Programı exe uzantısı ile paketle, böylece python yorumlayıcısı yüklü olmayan bilgisayarlarda da çalışabilsin.
2) Programın exe'sini (app.exe) çalıştırdığımızda ekranda herhangi bir pencere gözükmesin, arka planda çalışsın. Yani programın çalıştığını sadece görev yöneticisinden görebilelim. Yani, ekranda herhangi görünür bir penceresi olması.

Hadi bakalım. :)

**Comment by BatuHanHub** [comment]
Hocam yaptım! çalışıyor :D

**Comment by BatuHanHub** [comment]
Hocam Pyinstaller modülüyle programı .exe olarak paketledim. Konsolu göstermemesi için "--noconsole" komudunu yazdım. İcon komudu içinde "--icon=icon.ico" komudunu yazdım. Tek bir exe dosya olması için "--onefile" komudunu yazdım.
